services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: chefbawss
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5437:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8007:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env

volumes:
  postgres_data:
