# Generated by Django 5.2.1 on 2025-12-12 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('default_pay_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calendar_color', models.CharField(blank=True, max_length=7)),
                ('notes', models.TextField(blank=True, help_text='Admin-only private notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chef_profile', to='organizations.organizationmembership')),
            ],
        ),
    ]
