# Generated by Django 5.2.1 on 2025-12-12 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chefs', '0001_initial'),
        ('clients', '0001_initial'),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.TextField(blank=True)),
                ('guest_count', models.PositiveIntegerField()),
                ('allergies', models.TextField(blank=True)),
                ('menu_notes', models.TextField(blank=True)),
                ('client_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chef_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit_received', models.BooleanField(default=False)),
                ('internal_notes', models.TextField(blank=True, help_text='Admin only')),
                ('chef_notes', models.TextField(blank=True, help_text='Editable by assigned chef')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='chefs.chefprofile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='clients.client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organizations.organization')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
