# Generated by Django 5.2.1 on 2025-12-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payment_received',
            field=models.BooleanField(default=False),
        ),
    ]
