# Generated by Django 5.2.1 on 2026-04-22 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_add_payment_received'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
    ]
